name: ALZ-Bicep-4A-HubSpoke

on:
  push:
    branches:
      - "main"
    paths:
      - "config/custom-parameters/resourceGroupConnectivity.parameters.all.json"
      - "config/custom-parameters/hubNetworking.parameters.all.json"
  pull_request:
    branches:
      - "main"
    paths:
      - "config/custom-parameters/resourceGroupConnectivity.parameters.all.json"
      - "config/custom-parameters/hubNetworking.parameters.all.json"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  hubspoke_preflight:
    if: github.event_name == 'pull_request'
    name: Preflight validation
    needs: alz-bicep-1-core_canary
    uses: ./.github/workflows/reuse-hubspoke.yml
    with:
      environment: dev

  hubspoke_prod:
    name: Deploy to ALZ live
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: deploy_preflight
    uses: ./.github/workflows/reuse-hubspoke.yml
    with:
      environment: prod