name: ALZ-Bicep-3-SubPlacement

on:
  push:
    branches:
      - "main"
    paths:
      - "config/custom-parameters/subPlacementAll.parameters.all.json"
  pull_request:
    branches:
      - "main"
    paths:
      - "config/custom-parameters/subPlacementAll.parameters.all.json"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  subplacement_preflight:
    if: github.event_name == 'pull_request'
    name: Subplacement - Preflight ALZ Live
    uses: ./.github/workflows/reuse-subplacement.yml
    with:
      environment: dev

  subplacement_live:
    name: Subplacement - Deploy ALZ Live
    needs: subplacement_preflight
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/reuse-subplacement.yml
    with:
      environment: prod
