name: ALZ-Bicep-2-PolicyAssignments
on:
  push:
    paths:
      - alzDefaultPolicyAssignments.parameters.all.json
      - ".env"
  pull_request:
    branches:
      - "main"
    paths:
      - alzDefaultPolicyAssignments.parameters.all.json
      - ".env"
  workflow_dispatch:  

permissions:
  id-token: write
  contents: read

jobs:  
  policyassignments_canary_preflight:
    name: PolicyAssignments - Preflight ALZ Canary
    if: github.event_name != 'pull_request' && github.ref != 'refs/heads/main'
    uses: ./.github/workflows/reuse-policyassignments.yml
    with:
      environment: canary-preflight

  policyassignments_canary_deploy:
    name: PolicyAssignments - Deploy ALZ Canary
    if: github.event_name != 'pull_request' && github.ref != 'refs/heads/main'
    needs: policyassignments_canary_preflight
    uses: ./.github/workflows/reuse-policyassignments.yml
    with:
      environment: canary

  policyassignment_live_preflight:
    if: github.event_name == 'pull_request'
    name: PolicyAssignments - Preflight ALZ Live
    needs: policyassignments_canary_deploy
    uses: ./.github/workflows/reuse-policyassignments.yml
    with:
      environment: dev

  policyassignment_live_deploy:
    name: PolicyAssignments - Deploy ALZ Live
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: policyassignment_live_preflight
    uses: ./.github/workflows/reuse-policyassignments.yml
    with:
      environment: prod