name: ALZ-Bicep-4A-HubSpoke

on:
  push:
    branches:
      - "main"
    paths:
      - "config/custom-parameters/resourceGroupConnectivity.parameters.all.json"
      - "config/custom-parameters/hubNetworking.parameters.all.json"
      - ".env"
  pull_request:
    branches:
      - "main"
    paths:
      - "config/custom-parameters/resourceGroupConnectivity.parameters.all.json"
      - "config/custom-parameters/hubNetworking.parameters.all.json"
      - ".env"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  hubspoke_preflight:
    if: github.event_name == 'pull_request'
    name: HubSpoke - Preflight ALZ Live
    uses: ./.github/workflows/reuse-hubspoke.yml
    with:
      environment: dev

  hubspoke_live:
    name: HubSpoke - Deploy ALZ Live
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/reuse-hubspoke.yml
    with:
      environment: prod