name: ALZ-Bicep-1-Core
on:
  push:
    paths:
      - "config/custom-parameters/managementGroups.parameters.all.json"
      - "config/custom-parameters/customPolicyDefinitions.parameters.all.json"
      - "config/custom-parameters/customRoleDefinitions.parameters.all.json"
  pull_request:
    branches:
      - "main"
    paths:
      - "config/custom-parameters/managementGroups.parameters.all.json"
      - "config/custom-parameters/customPolicyDefinitions.parameters.all.json"
      - "config/custom-parameters/customRoleDefinitions.parameters.all.json"
  workflow_dispatch:  

permissions:
  id-token: write
  contents: read

jobs:  
  alz-bicep-1-core_preflight:
    name: ALZ-Bicep-1-Core - Preflight
    if: github.event_name != 'pull_request' && github.ref != 'refs/heads/main'
    uses: ./.github/workflows/reuse-core.yml
    with:
      environment: canary-preflight

  alz-bicep-1-core_canary:
    name: ALZ-Bicep-1-Core - ALZ Canary
    if: github.event_name != 'pull_request' && github.ref != 'refs/heads/main'
    needs: alz-bicep-1-core_preflight
    uses: ./.github/workflows/reuse-core.yml
    with:
      environment: canary

  deploy_preflight:
    if: github.event_name == 'pull_request'
    name: Preflight validation
    uses: ./.github/workflows/reuse-core.yml
    with:
      environment: dev

  deploy_prod:
    name: Deploy to ALZ live
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/reuse-core.yml
    with:
      environment: prod