name: ALZ-Bicep-1-Core
on:
  push:
    paths:
      - "config/custom-parameters/managementGroups.parameters.all.json"
      - "config/custom-parameters/resourceGroupLoggingAndSentinel.parameters.all.json"
      - "config/custom-parameters/logging.parameters.all.json"
      - "config/custom-parameters/customPolicyDefinitions.parameters.all.json"
      - "config/custom-parameters/customRoleDefinitions.parameters.all.json"
      - "config/custom-parameters/mgDiagSettingsAll.parameters.all.json"
      - ".env"
  pull_request:
    branches:
      - "main"
    paths:
      - "config/custom-parameters/managementGroups.parameters.all.json"
      - "config/custom-parameters/resourceGroupLoggingAndSentinel.parameters.all.json"
      - "config/custom-parameters/logging.parameters.all.json"
      - "config/custom-parameters/customPolicyDefinitions.parameters.all.json"
      - "config/custom-parameters/customRoleDefinitions.parameters.all.json"
      - "config/custom-parameters/mgDiagSettingsAll.parameters.all.json"
      - ".env"
  workflow_dispatch:  

permissions:
  id-token: write
  contents: read

jobs:  
  core_canary_preflight:
    name: Core - Preflight ALZ Canary
    if: github.event_name != 'pull_request' && github.ref != 'refs/heads/main'
    uses: ./.github/workflows/reuse-core.yml
    with:
      environment: canary-preflight

  core_canary_deploy:
    name: Core - Deploy ALZ Canary
    if: github.event_name != 'pull_request' && github.ref != 'refs/heads/main'
    needs: core_canary_preflight
    uses: ./.github/workflows/reuse-core.yml
    with:
      environment: canary

  core_live_preflight:
    if: github.event_name == 'pull_request'
    name: Core - Preflight ALZ Live
    uses: ./.github/workflows/reuse-core.yml
    with:
      environment: dev

  core_live_deploy:
    name: Core - Deploy ALZ Live
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/reuse-core.yml
    with:
      environment: prod