name: Azure Landing Zone Continuous Delivery
on:
  push:
    branches:
      - main
  workflow_dispatch:  

permissions:
  id-token: write
  contents: read

jobs:  
  deploy_prod:
    if: 
    name: Deploy to Prod
    uses: ./.github/workflows/alz-bicep-1-core.yml
    with:
      environment: prod