name: Azure Landing Zone Continuous Integration
on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:


permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  deploy_preflight:
    name: Deploy preflight
    uses: ./.github/workflows/reuse.yml
    with:
      environment: dev

  deploy_canary:
    if: (!github.event_name == 'pull_request')
    name: Deploy Canary
    needs: deploy_preflight
    uses: ./.github/workflows/reuse.yml
    with:
      environment: canary