name: Azure Landing Zone Continuous Integration
on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:


permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  deploy_preflight:
    if: github.event_name == 'pull_request'
    name: Deploy preflight
    uses: ./.github/workflows/alz-bicep-1-core.yml
    with:
      environment: dev

  deploy_canary:
    if: github.event_name != 'pull_request'
    name: Deploy Canary
    uses: ./.github/workflows/alz-bicep-1-core.yml
    with:
      environment: canary