name: Calling Workflow

on:
  workflow_dispatch:

jobs:
  deploy_dev:
    name: Deploy to Dev
    uses: ./.github/workflows/reuse.yml
    with:
      environment: dev
    secrets:
      PASSWORD: ${{ secrets.PASSWORD }}
      
  deploy_prod:
    name: Deploy to Prod
    needs: deploy_dev
    uses: ./.github/workflows/reuse.yml
    with:
      environment: prod
    secrets:
      PASSWORD: ${{ secrets.PASSWORD }}