name: Calling Workflow

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs: 
  deploy_prod:
    name: Deploy to Prod
    needs: deploy_dev
    uses: ./.github/workflows/reuse.yml
    with:
      environment: prod

  deploy_dev:
    name: Deploy to Dev
    uses: ./.github/workflows/reuse.yml
    with:
      environment: dev