name: Calling Workflow

on:
  workflow_dispatch:
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  deploy_dev:
    if: github.event_name == 'pull_request'
    name: Deploy to Dev
    uses: ./.github/workflows/reuse.yml
    with:
      environment: dev
      
  deploy_prod:
    name: Deploy to Prod
    uses: ./.github/workflows/reuse.yml
    needs: deploy_dev
    with:
      environment: prod