name: reuse-subplacement

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: environment to deploy to
        required: true

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  ENV_FILE: ".env"
  IS_PULL_REQUEST: ${{ (inputs.environment == 'dev') || (inputs.environment == 'canary-preflight') }}
  AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
  TOP_LEVEL_MG_PREFIX: ${{ vars.TOP_LEVEL_MG_PREFIX }}
  TOP_LEVEL_MG_DISPLAYNAME: ${{ vars.TOP_LEVEL_MG_DISPLAYNAME }}

jobs:
  ALZ_Bicep_3_SubPlacement:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Remove Quotation Marks from Environment File"
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Write-Host $ENV_FILE
            (Get-Content -Path $env:ENV_FILE -Encoding UTF8) | ForEach-Object {$_ -replace '"',''} | Out-File -FilePath $env:ENV_FILE -Encoding UTF8
          azPSVersion: "latest"

      - name: Import Environment Variables from File
        run: cat ${{ env.ENV_FILE }} >> $GITHUB_ENV

      - name: OIDC Login to Tenant
        uses: azure/login@v1
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: "Deploy Subscription Placement"
        uses: azure/powershell@v1
        with:
          inlineScript: |
            .\pipeline-scripts\Deploy-ALZSubscriptionPlacement.ps1
          azPSVersion: "latest"
