name: Called Workflow

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: environment to deploy to
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    
    steps:

    - name: Set up environment variable
      run: echo "WHAT_IF=${{ inputs.environment == 'dev' }}" >> $GITHUB_ENV

    - name: OIDC Login to Tenant
      uses: azure/login@v1
      with:
        client-id: ${{ vars.AZURE_CLIENT_ID }}
        tenant-id: ${{ vars.AZURE_TENANT_ID }}
        subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true 

    - name: Deploy Azure Resource Group
      uses: azure/powershell@v1
      with:
        inlineScript: |
          $WhatIfEnabled = [System.Convert]::ToBoolean($($env:WHAT_IF))
          New-AzResourceGroup -Name mytestrg -Location "westeurope" -WhatIf $WhatIfEnabled
        azPSVersion: "latest"